[package]
name = "testiron"
version = "0.1.0"
authors = ["sandisks <sandisks555@gmail.com>"]

description = "My Web Site"
license = "MIT"

[dependencies]
iron = "0.6.*"
time = "0.1.40"
#mysql_async = "0.19.0"
rustc-serialize = "*"
router = "*"

[lib]
name = "adder"
path = "adder/src/lib.rs"

