[package]
name = "adder"
version = "0.1.1"
authors = ["edidada <sandisks555@gmail.com>"]
edition = "2018"
description = "Extensible, Concurrency Focused Web Development in Rust."
license = "MIT"

[dependencies]


